### ISSUE TITLE
The Crystal Joe bug that has been reported countless times already

### ISSUE THREAD

**Issue by MaGMML2-engine** [MaGMML2-engine/bugs#16]
Submitter: Zieldak
https://cdn.discordapp.com/attachments/239398871351033858/288799661345472512/killme8.gif

Jewel Satellite destroys the incomplete projectile but not the sprite itself.

**Comment by nstbayless** [comment]
possibly fixed by stove?

StoveGuy (2017-03-07):
```
- fixed that stationary enemy bullets would just linger around if they are reflected by jewel satellite
```

haven't checked.

**Comment by Zieldak** [comment]
- This appears to be fixed now
