### ISSUE TITLE
MM2 Blocky - Unknown variable penetrate

### ISSUE THREAD

**Issue by MaGMML2-engine** [MaGMML2-engine/bugs#27]
Submitter: Zieldak
___
ERROR in
action number 1
of Other Event: User Defined 11
for object objBlockySprayRise:

Error in code at line 1:
   if other.penetrate != 2 {
           ^
at position 10: Unknown variable penetrate

**Comment by nstbayless** [comment]
when did this happen?

**Comment by Zieldak** [comment]
**FIXED**
