### ISSUE TITLE
MM4 Swimming mets glitch through solid things when they hit a ceiling

### ISSUE THREAD

**Issue by Zieldak** [MaGMML2-engine/bugs#29]
https://cdn.discordapp.com/attachments/227247016105869314/283643314090278912/swimmingmetbug.gif

**Comment by Zieldak** [comment]
https://cdn.discordapp.com/attachments/227247016105869314/283643314090278912/swimmingmetbug.gif

**Comment by MaGMML2-engine** [comment]
This has been fixed.
