### ISSUE TITLE
Upside-down Screw Bomber bullets are off

### ISSUE THREAD

**Issue by Zieldak** [MaGMML2-engine/bugs#35]
https://cdn.discordapp.com/attachments/239398871351033858/289286476657590272/screwbomber.gif
Bottom 3 bullets need to be lifted by 8 pixels.

**Comment by Zieldak** [comment]
https://cdn.discordapp.com/attachments/239398871351033858/289286476657590272/screwbomber.gif
Bottom 3 bullets need to be lifted by 8 pixels.

**Comment by MaGMML2-engine** [comment]
This has been fixed.
