### ISSUE TITLE
Hornet Chasers if you die and they're holding something. Wasn't this fixed before?

### ISSUE THREAD

**Issue by Zieldak** [MaGMML2-engine/bugs#54]
___
ERROR in
action number 1
of  Step Event
for object objHornetChaser:

In script sprite_get_xcenter_object:
Error in code at line 5:
   return round(v.x - v.sprite_xoffset + (v.sprite_width/2));
                  ^
at position 17: Unknown variable x

**Comment by MaGMML2-engine** [comment]
This has been fixed.
