### ISSUE TITLE
**Pause menu crashes**

### ISSUE THREAD

**Issue by Zieldak** [MaGMML2-engine/bugs#55]
When you have tons of weapons disabled at the same time, pressing up and right at the same time in the pause menu [...] will make the game crash.

**Comment by MaGMML2-engine** [comment]
![crash](https://cloud.githubusercontent.com/assets/26261216/24581909/83a3c40e-16d9-11e7-8023-0536ca65b07c.png)

This configuration reliably causes a crash.

**Comment by MaGMML2-engine** [comment]
This has been fixed.
